# Generated by Django 4.1.7 on 2023-03-13 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_alter_appointment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-date', '-start_time'], 'verbose_name_plural': 'Appointments'},
        ),
    ]
