# Generated by Django 4.1.7 on 2023-02-28 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('SUN', 'Sunday'), ('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THUR', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday')], max_length=5)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('reason_of_unavailability', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(max_length=300)),
                ('specialization', models.CharField(choices=[('Physician', 'Physician'), ('Dentist', 'Dentist'), ('Psychologist', 'Psychologist'), ('Pharmacist', 'Pharmacist'), ('Nurse', 'Nurse'), ('Dermatologist', 'Dermatologist'), ('Other', 'Other')], max_length=255)),
                ('years_of_experience', models.IntegerField()),
                ('clinic', models.CharField(max_length=255)),
                ('time_slot', models.DurationField()),
                ('address', models.CharField(max_length=255)),
            ],
        ),
    ]
