# Generated by Django 4.1.7 on 2023-03-01 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import patients.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('bio', models.CharField(max_length=300)),
                ('specialization', models.CharField(choices=[('Physician', 'Physician'), ('Dentist', 'Dentist'), ('Psychologist', 'Psychologist'), ('Pharmacist', 'Pharmacist'), ('Nurse', 'Nurse'), ('Dermatologist', 'Dermatologist'), ('Other', 'Other')], max_length=255)),
                ('years_of_experience', models.IntegerField()),
                ('clinic', models.CharField(max_length=255)),
                ('time_slot', models.DurationField()),
                ('address', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('patients.customuser',),
            managers=[
                ('objects', patients.managers.CustomUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='availability',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor'),
        ),
    ]
